### ISSUE TITLE
Define Index for cloudwatch-logs-to-elastic-cloud

### ISSUE THREAD

**Issue by HarveyEV** [blueimp/aws-lambda#3]
How would I define the specific index to write the cloudwatch logs to without a pipeline?

**Comment by blueimp** [comment]
The elasticsearch [index name is automatically derived from the log group name](https://github.com/blueimp/aws-lambda/blob/master/cloudwatch-logs-to-elastic-cloud/index.js#L111):

```js
const index = payload.logGroup
    .replace(/\W+|_+/g, '-')
    .replace(/^-/, '')
    .toLowerCase()
```

So you define the index by choosing a cloudwatch log group name.
