### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ajaysheoran2323** [blueimp/aws-lambda#7]
Hi, I am gettting below error:

```
{
    "errorMessage": null,
    "errorType": "InvalidCiphertextException",
    "stackTrace": [
        "Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)",
        "Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
    ]
}
```

**Comment by blueimp** [comment]
Hi @ajaysheoran2323,
unfortunately that is very little information and not enough to provide you with any guidance.

The stack trace only lists references to the AWS SDK, so I can't tell which of the provided AWS Lambda functions of this project you are using.

Therefore my advice to you is to always provide enough context that others can reproduce the problem.

**Comment by blueimp** [comment]
Closing this for now until more information is provided and this is identified as a bug.

**Comment by bgraf-zlab** [comment]
I received this error when my webhook environment variable setup was wrong. You have to use KMS to encrypt this value. Maybe this screenshot gives the correct hints:

<img width="1113" alt="Bildschirmfoto 2019-09-24 um 16 50 54" src="https://user-images.githubusercontent.com/28538610/65522829-a6e1af80-deeb-11e9-86b1-b4953fef041f.png">

Best,
Benjamin.

**Comment by blueimp** [comment]
Thanks for the comment @bgraf-zlab, that's very helpful.
